// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace lei.iOS
{
	public partial class MyMa : UIView
	{
		public MyMa (IntPtr handle) : base (handle)
		{
		}
	}
}
